version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000" # Проброс порта контейнера на хост
    volumes:
      - .:/app # Монтируем текущую директорию в контейнер
    depends_on:
      - db
  db:
    image: postgres:13 # Используйте контейнер PostgreSQL, если база данных PostgreSQL
    # image: mysql:5.7 # Используйте контейнер MySQL, если база данных MySQL
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/postgresql/data # Монтируем том для сохранения данных PostgreSQL
    # Для MySQL используйте аналогичный способ монтирования данных
