version: '3'
services:
  web:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/back_end

    depends_on:
      - db
  db:
    image: postgres:13 # Используйте контейнер PostgreSQL, если база данных PostgreSQL
    # image: mysql:5.7 # Используйте контейнер MySQL, если база данных MySQL
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/postgresql/data # Монтируем том для сохранения данных PostgreSQL
    # Для MySQL используйте аналогичный способ монтирования данных
