# Generated by Django 4.2.2 on 2023-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_verified_phone_number_user_is_verified_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.IntegerField(),
        ),
    ]
