# Generated by Django 4.2.5 on 2023-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
