# Generated by Django 4.2.5 on 2023-10-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_info',
            field=models.TextField(default=''),
        ),
    ]
